name: Arena

on:
  push:
    branches: [ "main", "Arena_v1_0", "Arena_v1_1", "Arena_v1_2" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        configuration: [Debug, Release]

    runs-on: ${{ matrix.os }}

    env:
      DOTNET_VERSION: 8.0.x
      SOLUTION_PATH: ArenaProject/ArenaProject.sln
      TEST_PROJECT_PATH: ArenaProject/ArenaTest/ArenaTest.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore ${{ env.SOLUTION_PATH }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_PATH }} --configuration ${{ matrix.configuration }} --no-restore

    - name: Test
      run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration ${{ matrix.configuration }} --no-build --verbosity normal
